apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sluice-internal
  namespace: sluice
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-porkbun
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik-internal
  tls:
    - hosts: [sluice.k8s.hraedon.com]
      secretName: sluice-internal-tls
  rules:
    - host: sluice.k8s.hraedon.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sluice
                port:
                  name: http
