apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sluice
resources:
- namespace.yaml
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml
- deployment.yaml
- service.yaml
- ingress-internal.yaml
- ingress-external.yaml
- networkpolicy.yaml
- poddisruptionbudget.yaml
images:
- name: ghcr.io/hraedon/sluice
  newName: ghcr.io/hraedon/sluice
  newTag: latest
